name: Deploy project laravel into VM

# Test ci-cd

on:
  pull_request:
    branches:
      - production
      - development
      - homologation

    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Acessar servidor remoto via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          # script: |
          #   whoami
          #   ls -al
          script: |
            cd /var/www/html/laravel-project-git
            git pull origin development
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
